modLoader = "javafml"
loaderVersion = "[36,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "actualmultiplehotbars"
version = "${version}"
displayName = "Actual Multiple Hotbars"
authors = "Hirtol"
description = '''
Add Factorio like hotbars (with their own inventory)
'''
#logoFile = ""

[[dependencies.actualmultiplehotbars]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.actualmultiplehotbars]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.actualmultiplehotbars]]
modId = "cloth_config"
mandatory = true
versionRange = "[4.0,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.actualmultiplehotbars]]
modId = "architectury"
mandatory = true
versionRange = "[1.24.35,)"
ordering = "AFTER"
side = "BOTH"