modLoader = "javafml"
loaderVersion = "[38,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "actualmultiplehotbars"
version = "${version}"
displayName = "Actual Multiple Hotbars"
authors = "Hirtol"
description = '''
Add Factorio like hotbars (with their own inventory)
'''
#logoFile = ""

[[dependencies.actualmultiplehotbars]]
modId = "forge"
mandatory = true
versionRange = "[38,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.actualmultiplehotbars]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.actualmultiplehotbars]]
modId = "cloth_config"
mandatory = true
versionRange = "[6.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.actualmultiplehotbars]]
modId = "architectury"
mandatory = true
versionRange = "[4.0.29,)"
ordering = "AFTER"
side = "BOTH"